/*
  # Department Knowledge Base - Initial Schema

  ## Overview
  Creates all tables needed for the knowledge base: uploads tracking,
  articles (wiki pages), and article sections. Also sets up full-text
  search and row level security.

  ## New Tables

  ### uploads
  Tracks every file uploaded by staff. Stores the path in Supabase Storage
  and the current processing status (pending → processing → done/error).
  - id: unique identifier
  - filename: original file name shown to user
  - file_path: path inside the 'uploads' storage bucket
  - file_type: 'pdf', 'docx', or 'txt'
  - file_size: bytes
  - status: 'pending' | 'processing' | 'done' | 'error'
  - error_msg: populated if processing fails
  - article_id: foreign key set once the article is created

  ### articles
  One wiki page per processed upload. Contains the title, summary, and tags
  generated by AI. Full-text search is powered by a tsvector column kept
  up to date by a trigger.
  - id, title, slug (URL-safe unique identifier), summary, tags (array)
  - search_vector: auto-maintained for Postgres FTS

  ### article_sections
  Each article is broken into ordered sections (like Wikipedia H2/H3 headings).
  Section body is stored as Markdown text.
  - heading, body (Markdown), level (2 or 3), position (ordering)

  ## Security
  - RLS enabled on all three tables
  - Public read access on articles and article_sections (wiki is read-only for visitors)
  - Uploads are service-role only (edge function writes; no user-facing read needed)

  ## Notes
  1. The pg_trgm extension is enabled for potential future fuzzy search
  2. A trigger keeps articles.search_vector current on insert/update
  3. Indexes cover slug lookups, FTS, tag arrays, and section ordering
*/

CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE EXTENSION IF NOT EXISTS unaccent;

-- ── articles ──────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS articles (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title         TEXT NOT NULL,
  slug          TEXT NOT NULL UNIQUE,
  summary       TEXT NOT NULL DEFAULT '',
  tags          TEXT[] NOT NULL DEFAULT '{}',
  upload_id     UUID,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  search_vector TSVECTOR
);

CREATE INDEX IF NOT EXISTS articles_slug_idx   ON articles (slug);
CREATE INDEX IF NOT EXISTS articles_search_idx ON articles USING GIN (search_vector);
CREATE INDEX IF NOT EXISTS articles_tags_idx   ON articles USING GIN (tags);

-- Keep search_vector updated automatically
CREATE OR REPLACE FUNCTION update_article_search_vector()
RETURNS TRIGGER AS $$
BEGIN
  NEW.search_vector :=
    setweight(to_tsvector('english', coalesce(NEW.title, '')),   'A') ||
    setweight(to_tsvector('english', coalesce(NEW.summary, '')), 'B');
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS articles_search_vector_trigger ON articles;
CREATE TRIGGER articles_search_vector_trigger
  BEFORE INSERT OR UPDATE ON articles
  FOR EACH ROW EXECUTE FUNCTION update_article_search_vector();

ALTER TABLE articles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can read articles"
  ON articles FOR SELECT
  USING (true);

CREATE POLICY "Service role can insert articles"
  ON articles FOR INSERT
  TO service_role
  WITH CHECK (true);

CREATE POLICY "Service role can update articles"
  ON articles FOR UPDATE
  TO service_role
  USING (true)
  WITH CHECK (true);

-- ── article_sections ──────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS article_sections (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  article_id UUID NOT NULL REFERENCES articles (id) ON DELETE CASCADE,
  heading    TEXT NOT NULL,
  body       TEXT NOT NULL DEFAULT '',
  level      INTEGER NOT NULL DEFAULT 2,
  position   INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS sections_article_idx ON article_sections (article_id, position);

ALTER TABLE article_sections ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can read sections"
  ON article_sections FOR SELECT
  USING (true);

CREATE POLICY "Service role can insert sections"
  ON article_sections FOR INSERT
  TO service_role
  WITH CHECK (true);

-- ── uploads ───────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS uploads (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  filename   TEXT NOT NULL,
  file_path  TEXT NOT NULL,
  file_type  TEXT NOT NULL,
  file_size  INTEGER NOT NULL DEFAULT 0,
  status     TEXT NOT NULL DEFAULT 'pending',
  error_msg  TEXT,
  article_id UUID REFERENCES articles (id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE uploads ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can insert uploads"
  ON uploads FOR INSERT
  WITH CHECK (true);

CREATE POLICY "Anyone can read own uploads"
  ON uploads FOR SELECT
  USING (true);

CREATE POLICY "Service role can update uploads"
  ON uploads FOR UPDATE
  TO service_role
  USING (true)
  WITH CHECK (true);
